from .parser import Parser
from .mvideo import MvideoParser
from .shveimash import ShveiMashParser
from .shveimashspb import ShveiMashSpbParser
from .sewing_kingdom import SewingKingdomParser
from .sewingking import SewingKingParser
from .textiletorg import TextiletorgParser
from .ozon import *
from .wildberries import WildberriesParser
from .holodilnik import HolodilnikParser
from .citilink import CitilinkParser
from .sewingstore import SewingStoreParser
from .dns import DNSParser
from .techport import TechPortParser
from .kcentr import KcentrParser
from .kulturabt import KulturabtParser
from .elecity import ElecityParser
from .sewingadvisor import SewingAdvisorParser
from .just import JustParser
from .becompact import BeCompactParser
from .oldi import OldiParser
from .elmall import ElMallParser
from .bit2 import Bit2Parser
from .skyey import SkyeyParser
from .cyberbelka import CyberBelkaParser
from .s123 import S123Parser
from .veritaz import VeritazParser
from .weektrade import WeekTradeParser
from .damadoma import DamaDomaParser
from .sewtime import SewTimeParser
