from .parser import Parser
from .mvideo import MvideoParser
from .shveimash import ShveiMashParser
from .shveimashspb import ShveiMashSpbParser
from .sewing_kingdom import SewingKingdomParser
from .sewingking import SewingKingParser
from .textiletorg import TextiletorgParser
from .ozon import OzonParser
from .wildberries import WildberriesParser
from .holodilnik import HolodilnikParser
from .citilink import CitilinkParser
from .sewingstore import SewingStoreParser
from .dns import DNSParser
from .techport import TechPortParser
from .kcentr import KcentrParser
from .kulturabt import KulturabtParser
from .elecity import ElecityParser
